/* ===========================================================================
The MIT License (MIT)

Copyright (c) 2022-2026 George Mavroeidis - GeoGraphics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
=========================================================================== */

#include "frame_buffer.h"

#include "Core/logger.h"

FrameBuffer::FrameBuffer(
    GLsizeiptr size,
    const void* data,
    const GLuint width,
    const GLuint height,
    const GLenum usage,
    const bool use_depth_texture,
    const char* debug_name)
    : Buffer(GL_FRAMEBUFFER, size, data, usage),
    m_width(width),
    m_height(height),
    m_use_depth_texture(use_depth_texture),
    m_debug_name(debug_name ? debug_name : "FrameBuffer")
{
    create_framebuffer();
    
    B3D_LOG_INFO("Frame Buffer Object '%s' with ID %d enabled (%s depth)", m_debug_name.c_str(), m_ID, m_use_depth_texture ? "sampled" : "renderbuffer");
}

FrameBuffer::FrameBuffer(
    const GLuint width,
    const GLuint height,
    const GLuint shared_depth_texture,
    const char* debug_name)
    : Buffer(GL_FRAMEBUFFER, 0, nullptr, GL_NONE),
    m_width(width),
    m_height(height),
    m_use_depth_texture(true),
    m_owns_depth_texture(false),
    m_debug_name(debug_name ? debug_name : "FrameBuffer")
{
    m_depth_texture = shared_depth_texture;
    create_framebuffer();

    B3D_LOG_INFO("Frame Buffer Object '%s' with ID %d enabled (sharing external depth texture %d)", m_debug_name.c_str(), m_ID, m_depth_texture);
}

FrameBuffer::~FrameBuffer()
{
    destroy_framebuffer();
}

void FrameBuffer::bind() const
{
    glBindFramebuffer(m_target, m_ID);
    glViewport(0, 0, m_width, m_height);
}

void FrameBuffer::unbind() const // when unbinding a frame buffer, it binds back to default
{
    glBindFramebuffer(m_target, 0);
    glViewport(0, 0, m_width, m_height);
}

void FrameBuffer::resize(const GLuint new_width, const GLuint new_height, const GLuint new_shared_depth_texture)
{
    // A non-owned depth texture is regenerated by its owner on every resize (new GL texture
    // ID each time), the caller must pass the fresh ID or this FrameBuffer would silently
    // keep attaching a deleted texture.
    const bool depth_target_changed = !m_owns_depth_texture
        && new_shared_depth_texture != 0
        && new_shared_depth_texture != m_depth_texture;

    if (m_width != new_width || m_height != new_height || depth_target_changed)
    {
        m_width = new_width;
        m_height = new_height;

        if (depth_target_changed)
        {
            m_depth_texture = new_shared_depth_texture;
        }

        destroy_framebuffer();
        create_framebuffer();
    }
}

void FrameBuffer::resolve_to(const FrameBuffer* fbo_target) const
{
    assert(m_width == fbo_target->get_width() && m_height == fbo_target->get_height());

    glBindFramebuffer(GL_READ_FRAMEBUFFER, m_ID);
    glBindFramebuffer(GL_DRAW_FRAMEBUFFER, fbo_target->get_id());

    // Explicitly resolve the scene color attachment.
    glReadBuffer(GL_COLOR_ATTACHMENT0);
    glDrawBuffer(GL_COLOR_ATTACHMENT0);

    glBlitFramebuffer(
        0, 0,
        m_width, m_height,
        0, 0,
        fbo_target->get_width(),
        fbo_target->get_height(),
        GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT | GL_STENCIL_BUFFER_BIT,
        GL_NEAREST);

    glBindFramebuffer(GL_READ_FRAMEBUFFER, 0);
    glBindFramebuffer(GL_DRAW_FRAMEBUFFER, 0);
}

void FrameBuffer::clear() const
{
    // Accum starts at zero (nothing accumulated yet)
    // Revealage starts at 1.0 (background fully visible) since it's a product accumulator.
    constexpr float accum_clear[4]  = { 0.0f, 0.0f, 0.0f, 0.0f };
    constexpr float reveal_clear[4] = { 1.0f, 1.0f, 1.0f, 1.0f };
    glClearBufferfv(GL_COLOR, 0, accum_clear);
    glClearBufferfv(GL_COLOR, 1, reveal_clear);
}

void FrameBuffer::bind_color_attachment(const GLuint index) const
{
    if (index >= m_color_textures.size())
    {
        B3D_LOG_ERROR("FrameBuffer '%s': color texture index %zu out of range (%zu attachments).", m_debug_name.c_str(), index, m_color_textures.size());
        return;
    }
    glActiveTexture(GL_TEXTURE0 + index);
    glBindTexture(GL_TEXTURE_2D, get_color_texture(index));
}

float FrameBuffer::get_aspect_ratio() const
{
    if (m_height == 0)
    {
        return 1.0f;
    }
    return static_cast<float>(m_width) / static_cast<float>(m_height);
}

GLuint FrameBuffer::get_color_texture(const GLuint index) const
{
    if (index >= m_color_textures.size())
    {
        B3D_LOG_ERROR("FrameBuffer '%s': color texture index %zu out of range (%zu attachments).", m_debug_name.c_str(), index, m_color_textures.size());
        return 0;
    }
    return m_color_textures[index];
}

std::vector<GLenum> FrameBuffer::get_draw_buffers() const
{
    return { GL_COLOR_ATTACHMENT0 };
}

std::string FrameBuffer::get_color_attachment_label(const size_t index) const
{
    return index == 0 ? "_Color" : ("_Color" + std::to_string(index));
}

void FrameBuffer::create_attachments()
{
    create_texture_2d_attachment(GL_COLOR_ATTACHMENT0, GL_RGBA16F, GL_RGBA, GL_UNSIGNED_BYTE);

    if (m_use_depth_texture)
    {
        if (m_owns_depth_texture)
        {
            glGenTextures(1, &m_depth_texture);
            glBindTexture(GL_TEXTURE_2D, m_depth_texture);

            glTexImage2D(GL_TEXTURE_2D, 0, GL_DEPTH24_STENCIL8, m_width, m_height, 0,
                         GL_DEPTH_STENCIL, GL_UNSIGNED_INT_24_8, nullptr);

            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);

            glTexParameteri(GL_TEXTURE_2D, GL_DEPTH_STENCIL_TEXTURE_MODE, GL_DEPTH_COMPONENT);
            glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_COMPARE_MODE, GL_NONE);

            glFramebufferTexture2D(m_target, GL_DEPTH_STENCIL_ATTACHMENT, GL_TEXTURE_2D, m_depth_texture, 0);
        }
        else
        {
            attach_shared_depth_texture();
        }
    }
    else
    {
        glGenRenderbuffers(1, &m_rbo);
        glBindRenderbuffer(GL_RENDERBUFFER, m_rbo);
        glRenderbufferStorage(GL_RENDERBUFFER, GL_DEPTH24_STENCIL8, m_width, m_height);
        glFramebufferRenderbuffer(m_target, GL_DEPTH_STENCIL_ATTACHMENT, GL_RENDERBUFFER, m_rbo);
    }
}

GLuint FrameBuffer::create_texture_2d_attachment(
    const GLenum attachment_slot,
    const GLenum internal_format,
    const GLenum format,
    const GLenum type,
    const GLenum min_filter,
    const GLenum mag_filter,
    const bool track_as_output)
{
    GLuint texture_id;
    glGenTextures(1, &texture_id);
    glBindTexture(GL_TEXTURE_2D, texture_id);
    glTexImage2D(GL_TEXTURE_2D, 0, internal_format, m_width, m_height, 0, format, type, nullptr);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, min_filter);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, mag_filter);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glFramebufferTexture2D(m_target, attachment_slot, GL_TEXTURE_2D, texture_id, 0);

    if (track_as_output)
    {
        m_color_textures.push_back(texture_id);
    }
    return texture_id;
}

void FrameBuffer::attach_shared_depth_texture() const
{
    if (m_use_depth_texture && !m_owns_depth_texture && m_depth_texture != 0)
    {
        glFramebufferTexture2D(m_target, GL_DEPTH_STENCIL_ATTACHMENT, GL_TEXTURE_2D, m_depth_texture, 0);
    }
}

void FrameBuffer::label_resources() const
{
    glObjectLabel(GL_FRAMEBUFFER, m_ID, -1, m_debug_name.c_str());

    for (size_t i = 0; i < m_color_textures.size(); ++i)
    {
        const std::string label = m_debug_name + get_color_attachment_label(i);
        glObjectLabel(GL_TEXTURE, m_color_textures[i], -1, label.c_str());
    }

    if (m_use_depth_texture && m_owns_depth_texture)
    {
        const std::string depth_label = m_debug_name + "_Depth";
        glObjectLabel(GL_TEXTURE, m_depth_texture, -1, depth_label.c_str());
    }
    else if (m_rbo != 0)
    {
        const std::string depth_label = m_debug_name + "_DepthStencilRBO";
        glObjectLabel(GL_RENDERBUFFER, m_rbo, -1, depth_label.c_str());
    }
    // Non-owned depth texture already carries label from original created buffer
}

void FrameBuffer::create_framebuffer()
{
    if (m_target != GL_FRAMEBUFFER)
    {
        B3D_LOG_ERROR("Framebuffer target is not correct. Must be GL_FRAMEBUFFER.");
    }

    glGenFramebuffers(1, &m_ID);
    glBindFramebuffer(m_target, m_ID);

    create_attachments();

    const std::vector<GLenum> draw_buffers = get_draw_buffers();
    if (draw_buffers.empty())
    {
        glDrawBuffer(GL_NONE);
        glReadBuffer(GL_NONE);
    }
    else
    {
        glDrawBuffers(static_cast<GLsizei>(draw_buffers.size()), draw_buffers.data());
    }

    // Verify framebuffer is complete
    if (const GLenum status = glCheckFramebufferStatus(m_target); status != GL_FRAMEBUFFER_COMPLETE)
    {
        B3D_LOG_ERROR("Framebuffer %s is not complete! Status: 0x%x", m_debug_name, status);
    }

    label_resources();

    glBindFramebuffer(m_target, 0);
    glBindTexture(GL_TEXTURE_2D, 0);
}

void FrameBuffer::destroy_framebuffer()
{
    if (m_ID != 0)
    {
        glDeleteFramebuffers(1, &m_ID);
        m_ID = 0;
    }
    for (const GLuint texture : m_color_textures)
    {
        glDeleteTextures(1, &texture);
    }
    m_color_textures.clear();
    if (m_rbo != 0)
    {
        glDeleteRenderbuffers(1, &m_rbo);
        m_rbo = 0;
    }

    // Only delete the depth-stencil texture if THIS framebuffer owns it.
    // Non-owning framebuffers merely reference r_main_fbo's depth texture.
    // Deleting it here would silently invalidate every framebuffer sharing that same GL resource,
    // where no other framebuffer gets notified of it.
    if (m_owns_depth_texture && m_depth_texture != 0)
    {
        glDeleteTextures(1, &m_depth_texture);
        m_depth_texture = 0;
    }
}

MultisampleFrameBuffer::MultisampleFrameBuffer(
    const GLuint width,
    const GLuint height,
    const GLsizei samples,
    const char* debug_name)
    : FrameBuffer(0, nullptr, width, height, GL_NONE, false, debug_name ? debug_name : "MSAAFrameBuffer"),
    m_samples(samples),
    m_max_samples(0)
{
    glGetIntegerv(GL_MAX_SAMPLES, &m_max_samples);

    // Validate the requested samples against the hardware limit.
    // Fallback to a safe default if invalid.
    if (samples < 1 || samples > m_max_samples || (samples & (samples - 1)) != 0)
    {
        B3D_LOG_ERROR("Invalid MSAA sample count: %d. Must be power of two or greater than the hardware limit: %d.", samples, m_max_samples);
        m_samples = 4;
    }
    // FrameBuffer constructor already called create_framebuffer(). Redo it for this one.
    destroy_framebuffer();
    create_framebuffer();

    B3D_LOG_INFO("MSAA Frame Buffer Object enabled...");
}

void MultisampleFrameBuffer::set_samples(const GLsizei new_samples)
{
    if (new_samples < 1 || new_samples > m_max_samples || (new_samples & (new_samples - 1)) != 0)
    {
        B3D_LOG_ERROR("Invalid sample count: %d. Must be a power of two between 1 and 8.", new_samples);
        return;
    }
    if (m_samples != new_samples)
    {
        m_samples = new_samples;
        destroy_framebuffer();
        create_framebuffer();
        
        B3D_LOG_INFO("Resampling MSAA Frame Buffer Object to %dx%d samples...", m_samples, m_samples);
    }
}

void MultisampleFrameBuffer::create_attachments()
{
    GLuint texture_id;
    glGenTextures(1, &texture_id);
    glBindTexture(GL_TEXTURE_2D_MULTISAMPLE, texture_id);
    glTexImage2DMultisample(GL_TEXTURE_2D_MULTISAMPLE, m_samples, GL_RGBA16F, m_width, m_height, GL_TRUE);
    glBindTexture(GL_TEXTURE_2D_MULTISAMPLE, 0);
    glFramebufferTexture2D(m_target, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D_MULTISAMPLE, texture_id, 0);
    m_color_textures.push_back(texture_id);

    glGenRenderbuffers(1, &m_rbo);
    glBindRenderbuffer(GL_RENDERBUFFER, m_rbo);
    glRenderbufferStorageMultisample(GL_RENDERBUFFER, m_samples, GL_DEPTH24_STENCIL8, m_width, m_height);
    glBindRenderbuffer(GL_RENDERBUFFER, 0);
    glFramebufferRenderbuffer(m_target, GL_DEPTH_STENCIL_ATTACHMENT, GL_RENDERBUFFER, m_rbo);
}

WBOITFrameBuffer::WBOITFrameBuffer(const GLuint width, const GLuint height, const GLuint shared_depth_texture, const char* debug_name)
    : FrameBuffer(width, height, shared_depth_texture, debug_name ? debug_name : "WBOITFrameBuffer")
{
    // FrameBuffer constructor already called create_framebuffer(). Redo it for this one.
    destroy_framebuffer();
    create_framebuffer();

    B3D_LOG_INFO("WBOIT Frame Buffer Object enabled...");
}

void WBOITFrameBuffer::create_attachments()
{
    // Accumulation: additive sum of (color * alpha * weight) across overlapping particles (with float precision and an unclamped range)
    create_texture_2d_attachment(GL_COLOR_ATTACHMENT0, GL_RGBA16F, GL_RGBA, GL_FLOAT);

    // Revealage: product of (1 - alpha) across overlapping fragments.
    create_texture_2d_attachment(GL_COLOR_ATTACHMENT1, GL_R8, GL_RED, GL_FLOAT);

    attach_shared_depth_texture();
}

std::vector<GLenum> WBOITFrameBuffer::get_draw_buffers() const
{
    return { GL_COLOR_ATTACHMENT0, GL_COLOR_ATTACHMENT1 };
}

std::string WBOITFrameBuffer::get_color_attachment_label(const size_t index) const
{
    // Only two color attachments exist in this type of frame buffer
    return index == 0 ? "_Accum" : "_Revealage";
}
